os:
  - linux
dist: trusty
language: node_js
node_js:
  - node
  - 8
  - 7
  - 6
before_install:
  - npm config set depth 0
script:
  - npm run lint
  - npm run test
  - npm run build
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 80
after_success:
  - npm run build
  - semantic-release pre
  - npm publish
  - semantic-release post
notifications:
  email: false
before_script:
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - curl -L https://raw.githubusercontent.com/GoogleChrome/lighthouse/v2.1.0/lighthouse-core/scripts/download-chrome.sh | bash
